### ISSUE TITLE
Enable legacy mode to specify  LoraWan providers manually

### ISSUE THREAD

**Issue by krasi-georgiev** [PiSupply/iot-lora-controller#20] opened 2019-07-11 10:15 UTC
IIUC it is called legacy mode and it will allow specifying server IP/Domain and not having it hard coded to TTN.

In my case the setup doesn't have an internet connection so will just configure the packet forwarder to send to `localhost` and build a dummy server which will be installed on the same RPI and parse the received data.

**Comment by krasi-georgiev** [comment] 2019-07-11 10:25
looks related to https://github.com/PiSupply/iot-lora-controller/issues/2

**Comment by ryanteck** [comment] 2019-07-15 20:22
I'm going to close this ticket as I did forget one was already open. 

Duplicate of #2

**Closed by ryanteck** 2019-07-15 20:22 UTC
